services:
  web_server:
    build: ./Roll_and_Reserve_DataBase
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - database
      - mongodb
      #- redis
    container_name: Roll_and_Reserve-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./Roll_and_Reserve:/web
    environment:
      - TZ=Europe/Berlin
  flutter:
    build: ./Roll_and_Reserve_App
    depends_on:
      - web_server
    ports:
      - 8080:8080
    container_name: Roll_and_Reserve-flutter
    volumes:
      - ./2dam_inventory:/app
    environment:
      - TZ=Europe/Berlin

  database:
    image: yobasystems/alpine-mariadb:10.11.8
    container_name: Roll_and_Reserve-db
    ports:
      - "2222:3306"
    #restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
    volumes:
     - ./data/db/mysql:/var/lib/mysql
    # - ./mysql.cnf:/etc/mysql/my.cnf
  mongodb:
    image: mongo:noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo-data:/data/db
  #redis: 
  #  image: 'redis'
  #  container_name: Roll_and_Reserve-redis
